Wfe luigi
code-squad/javascript-middle-mission pull request #10
Opened 2017-10-19 06:53 UTC by wfe-luigi

중간 추가 미션

2017-10-19 07:07 UTC, crongro requested changes

2017-10-19 07:07 UTC, nigayo commented on mission2.js
> +        else if (typeof (obj[property]) == 'object') getNumber(obj[property])
typeof 말고 다른 걸로 object 체크를 해보세요.
typeof의 한계도 좀더 공부하면 좋겠습니다.

2017-10-20 01:07 UTC, wfe-luigi commented on mission2.js
> +        else if (typeof (obj[property]) == 'object') getNumber(obj[property])
네

2017-10-23 01:03 UTC, crongro approved these changes
수고하셨어요.
객체에 대한 이해가 좀더 되셨기를~

2017-10-23 01:03 UTC, nigayo commented on mission2.js
> +        else if (obj[property].constructor == Object || obj[property].constructor == Array)
참고로, 다양한 type체크 방법을 더 찾아보세요~

2017-10-23 01:34 UTC, crongro approved these changes

2017-10-23 01:35 UTC, merged