자판기 제작
code-squad/javascript-middle-mission pull request #11
Opened 2017-10-20 01:27 UTC by Eclatant

* 사용자 입력을 받기 위해 readline 사용
* data를 보관하는 객체를 생성
* map property는 drinks에서 name에 해당하는 property에 바로 접근하기 위해 보관
* helper에서는 안내 및 에러용 message와 간단한 event를 보관
* 거래를 처리하기 위한 transaction
* 현재 잔액과 재고 등을 파악해서 처리해주는 controller
* 잔액이 부족할 때, 충전여부를 확인하고 처리하기 위한 chargeWhether
* 음료를 선택받아 전달하기 위한 selectDrink
* 잔액 충전시 처리하기 위한 chargeAccount

2017-10-21 04:59 UTC, crongro requested changes

2017-10-21 04:59 UTC, nigayo commented on Eclatant/자판기.js
> +function transaction(productName) {
두 개가 같은 이름일 필요는 없겠네요.

2017-10-21 04:59 UTC, nigayo commented on Eclatant/자판기.js
> +      log("현재 재고가 남아있는 제품이 하나도 없습니다. 돈을 반환해드리겠습니다.");
이런 메시지도 helper 메시지로 옮길 수 없나요 ?

2017-10-21 04:59 UTC, nigayo commented on Eclatant/자판기.js
> +    data.drinks.filter(function(drink) {
if 문안의 내용이 너무 길~~어요

2017-10-21 04:59 UTC, nigayo commented on Eclatant/자판기.js
> +  rl.question("금액을 투입해주십시오. ", function(input) {
반복적으로 모든 함수에서 input을 받는 로직이 들어가 있는데, 이 진입점을 하나로 해보는 건 어때요? 
많은 함수가 비동기로직이 들어가 있고,  재귀호출을 하고 있어서 좀 복잡해보여요.

그리고 object literal로 변경해보시면서 개선하는 것도 좋고요.
object literal로 할때는 하나의 객체로 담지말고, 2개정도로 나눠서 만들어보세요.

var a = {}
var b = {}

2017-10-22 06:17 UTC, Eclatant commented on Eclatant/자판기.js
> +function transaction(productName) {
@nigayo 

transaction 과 productName 중 어느 것을 지칭해주신 것일까요~?

2017-10-22 10:20 UTC, Eclatant commented on Eclatant/자판기.js
> +  rl.question("금액을 투입해주십시오. ", function(input) {
@nigayo 

진입점을 한 곳으로 줄이는 작업을 오늘 하루 종일 해보았으나,
이전 코드에 비해서 난이도가 훨씬 높아서 실패하였습니다.

괜찮으시다면, 현재 막힌 부분을 내일 함께 풀어볼 수 있으면 좋을 것 같습니다...

2017-10-23 00:53 UTC, nigayo commented on Eclatant/자판기.js
> +function transaction(productName) {
transaction 메서드가 동일한이름이 두개 보이길래 한 이야기입니다.

2017-10-24 06:20 UTC, nigayo commented
머지합니다.

2017-10-24 06:20 UTC, merged