자판기 애플리케이션
code-squad/javascript-middle-mission pull request #12
Opened 2017-10-23 02:41 UTC by wfe-luigi

2017-10-23 06:27 UTC, crongro requested changes
잘 구현하셨고요. 
조금만 더 수정해보세요.

2017-10-23 06:27 UTC, nigayo commented on mission3.js
> +function buy(name, haveMoney) {
함수이름은 좀더 구체적으로 작성해요.

2017-10-23 06:27 UTC, nigayo commented on mission3.js
> +    for (property in drinks) {
drinks는 전역에 있는 변수인데요, 함수에서 바로 전역변수를 불러서 쓰지않고, 함수의 인자로 받아서 처리하도록해요.

2017-10-23 06:27 UTC, nigayo commented on mission3.js
> +        if (answer == "반환") {
== 와 === 의 차이는 좀 커요. 
찾아보세요~

2017-10-23 06:27 UTC, nigayo commented on mission3.js
> +function printMsg() {
범용함수로 잘만드셨네요.

2017-10-23 06:28 UTC, nigayo commented
아 그리고 commit 로그가 너무 없습니다.
이렇게 하시면 안됩니다.

2017-10-23 08:26 UTC, wfe-luigi commented on mission3.js
> +function printMsg() {
네

2017-10-23 08:26 UTC, wfe-luigi commented on mission3.js
> +function buy(name, haveMoney) {
네

2017-10-23 08:27 UTC, wfe-luigi commented on mission3.js
> +    for (property in drinks) {
네

2017-10-23 08:27 UTC, wfe-luigi commented on mission3.js
> +        if (answer == "반환") {
네

2017-10-23 09:07 UTC, crongro requested changes
코멘트 단 부분 다시 확인해보세요.

2017-10-23 09:07 UTC, nigayo commented on mission3.js
> +    for (property in obj) {
여기 아래 for문 아래 if 문 안에  if문이 있는데요.
이를 개선해볼 수 있을거 같아요.

2017-10-23 09:07 UTC, nigayo commented on mission3.js
> +        if (answer == "반환") {
=== 만을 사용하는게 더 좋아요.

2017-10-23 10:06 UTC, wfe-luigi commented on mission3.js
> +    for (property in obj) {
네

2017-10-24 00:35 UTC, crongro approved these changes
수고하셨어요. 
코멘트 다시 돌아보면서 정리하시고 다음step으로 가보죠~

2017-10-24 00:35 UTC, nigayo commented on mission3.js
> +    for (property in obj) {
별건 아니지만, if 다음은 그냥 else겠네요~

2017-10-24 06:21 UTC, merged