Lotto function
code-squad/javascript-middle-mission pull request #18
Opened 2018-01-17 02:05 UTC by likedemian

2018-01-17 10:00 UTC, crongro requested changes
오 많은 발전이 보입니다.

개선점을 좀 남았어요.

지치지 말고 리뷰보고 좀더 로또완성해봅시다.

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +    let tickets = money / 1000
요구사항이 없지만, 1000원 단위가 아니면 에러를 뱉도록 하면 어떻게 구현해야 할까요?

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +let PRIZEMONEY = 0;
전역에 관리하는 변수들의 이름을 대문자로만 표현했네요. 나름대로 구분이 되서 나쁘지 않아요.
그런데, 객체형태로 이녀석들을 묶어서 하나의 전역변수만 유지할 수도 있겠네요.
해보세요~

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +      PICKS.push(insertNum(i));
여기서 전달하는 i 값은 실제 쓰지 않는듯하네요.

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +  for (let i = 1; i <= 45; i++) {
이 루프는 insertNum이 불릴때마다 똑같은 결과를 만드는 걸 반복하는 거 같은데요.
그렇다면 비효율적인 거 같아요.

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +    for (var i = 0; i < lottoArray.length; i++) {
요 코드를 forEach를 써볼래요?

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +  for (let val in arr) {
array 인데 왜 for in 을쓰죠? 
for-in은 객체를 탐색할때 사용해요.

2018-01-17 10:00 UTC, nigayo commented on lotto.js
> +    if (result[val] === 3) {
3이면 5000원, 
4이면 50000원..

이런 룰이 변경되거나 추가된다고 가정하면, 계속 if문이 변경되고 추가 될 텐데요.
 if문을 안쓴다거나,,아니면  줄여서 좀더 간단한 코드를 만드는게 가능할까요?

2018-01-18 08:55 UTC, crongro requested changes
좀 수정해보죠~!

2018-01-18 08:55 UTC, nigayo commented on lotto.js
> +    let reg = /^\d{0,9}000$/
\d{0,9} -> \d?

2018-01-18 08:55 UTC, nigayo commented on lotto.js
> +    const thousands = (num) => {
함수이름의 규칙을 항상지키세요. 동사+명사.

2018-01-18 08:55 UTC, nigayo commented on lotto.js
> +      console.log("다시 입력해 주세요.");
에러메시지는 '무엇이 문제인지, 어떻게 처리해야할지를 알려주는 게 더 좋아요' 
개발자에게건, 사용자에게건.

2018-01-18 08:55 UTC, nigayo commented on lotto.js
> +  PRIZEMONEY: 0,
전역변수 이름을 좀 줄이면 좋겠고요.
key값이 대문자니까, 너무 보기 어려워요.

2018-01-18 08:55 UTC, nigayo commented on lotto.js
> +  for (let i = 0; i < INIT_OBJECTS.RESULT.length; i++) {
요놈을 비롯해서 모든 반복문을 forEach나 map을 학습해서 바꿔볼래요?

2018-01-18 14:21 UTC, likedemian commented on lotto.js
> +    let reg = /^\d{0,9}000$/
/^\d?000$/ 라고 입력했는데, 10000 이상 숫자가 입력이 안됩니다 ㅠㅠ

2018-01-19 02:39 UTC, nigayo commented on lotto.js
> +    let reg = /^\d{0,9}000$/
아.. 착각했음 제가 ㅎ

2018-01-19 02:44 UTC, crongro requested changes
잘하셨네요.

좀더 수정해보고, 계속 완성해보세요.

본인생각을 담아서 리팩토링 좀더 해보죠.

2018-01-19 02:44 UTC, nigayo commented on lotto.js
> +      console.log("금액은 1000원 단위로 입력해야 합니다. 다시 입력해 주세요.");
msg도 INIT처럼 message를 모아둔 객체를 만들어보시죠.

2018-01-19 02:44 UTC, nigayo commented on lotto.js
> +    totalPrize += getPrize[elem];
요기 있던 if문은 없어졌네요. 
이 위치관점에서는 좋아진거 같은데요?

2018-01-19 02:44 UTC, nigayo commented on lotto.js
> +  let getPrize = {
이 코드도 compareResult 함수에서 관리해도 되지만, 외부에서 데이터를 묶어서 관리할 수도 있을 듯.

2018-01-22 02:08 UTC, crongro approved these changes
다음엔 반복문을 for문대신,
forEach, map 과 같은 메서드를 더 많이 쓸 수 있게 해보세요.

2018-01-22 02:08 UTC, nigayo commented on lotto.js
> +let MSG = {
메시지는 이렇게 객체로 분리하는게 젤 좋을 듯.

2018-01-22 02:08 UTC, merged