vending machine
code-squad/javascript-middle-mission pull request #20
Opened 2018-03-13 12:54 UTC by amorfati0310

vending machine review 부탁 드리겠습니다 👍

2018-03-15 02:50 UTC, crongro requested changes
열심히 개발하고 계시네요~

2018-03-15 02:50 UTC, crongro commented on lottoMachine/index.js
> +    for (let i = array.length - 1; i > 0; i--) {
shffleLottos메서드를 추가하 하나 더 만들어보면 좋겠어요.

이 코드랑 합쳐서  [...Array(45).keys()].map(x => x + 1);

다른 알고리즘으로(성능은 별로 고려하지 않고) 한번 구현해보세요

2018-03-15 02:50 UTC, nigayo commented on lottoMachine/index.js
> +    for (let i = 0; i < counts; i++) {
여기 for문도 배열의 foreach등의 메서드를 활용해 보세요.

2018-03-15 02:50 UTC, nigayo commented on lottoMachine/index.js
> +    this.getResult(lottos);
this.getResult(lottos); 는 result를 반환하는 함수일 거 같은데 그렇지 않네요.

2018-03-15 02:50 UTC, nigayo commented on vendingMachine/index.js
> +    displays.map(drink => {
여기서 map이 적절한 함수일까요?

2018-03-15 02:50 UTC, nigayo commented on lottoMachine/index.js
> +    sameNumbers.map(item => {
map의 반환값을 받는 곳이 없네요?

2018-03-16 03:10 UTC, crongro requested changes
리뷰참고하세요.
그리고 constructor 안에 있는 this.xx 속성들 중에, 
각 함수안으로 이동해서 지역변수로 옮길 수 있는 게 몇 개 있으면, 옮기세요. 
객체안에서 관리해야 할 상태값을 그렇게 this에 넣어둘 수는 있는데요,  이게 또 안좋은게,  클래스안에 있는 전역변수라고 할 수 있습니다. 그래서 줄일 수 있는 건 메서드 안으로 옮겨서 줄여주는게 좋아요.

2018-03-16 03:10 UTC, nigayo commented on lottoMachine/index.js
> +    let isUnique = randomIdx => randomIdxList.every(item => item !== randomIdx);
every를 잘 이해한거죠? 괜찮은방법이에요.
indexOf메서드를 쓸 수도 있을거고요.

2018-03-16 03:10 UTC, nigayo commented on lottoMachine/index.js
> +    let randomIdx;
randomIdx변수는 block scope안에서만 유효하면 함수초반에 선언하지 않아도 되겠네요.

전체코드에서 이런 부분이 있는지 쭉 살펴보고 있으면 수정해주세요.

2018-03-16 03:10 UTC, nigayo commented on lottoMachine/index.js
> +    randomIdxList.sort((a, b) => a - b).map(item => {
map은... 배열을 반환하는 함수이라 여기서, 최선은 아닐 거 같아요.
다른 배열메서드는 어때요?

2018-03-16 03:10 UTC, nigayo commented on lottoMachine/index.js
> +    let rate = (this.winningMoney / this.spendMoney).toFixed(4) * 100;
4와 같은 변경이 될 듯한 숫자는 파라미터로 받는 게 가능하면 그렇게 하죠.

2018-03-16 04:52 UTC, amorfati0310 reviewed
감사합니다 반영해서 얼른 수정해보겠습니다 👍

2018-03-16 04:52 UTC, amorfati0310 commented on lottoMachine/index.js
> +    for (let i = array.length - 1; i > 0; i--) {
네엡 감사합니다 👍

2018-03-16 04:52 UTC, amorfati0310 commented on lottoMachine/index.js
> +    for (let i = 0; i < counts; i++) {
여기서는 counts가 단순 숫자여서 for문을 썼는데  forEach call로 사용할까요?.?

2018-03-16 04:52 UTC, amorfati0310 commented on lottoMachine/index.js
> +    this.getResult(lottos);
감사합니다 네이밍을 좀 수정해야 될 것 같습니다 👍

2018-03-16 04:52 UTC, amorfati0310 commented on lottoMachine/index.js
> +    sameNumbers.map(item => {
넵 바로 돌면서 콘솔로 찍도록 만들었는데 값을 넘겨서 따로 프린트 하도록 수정해보겠습니다

2018-03-16 04:52 UTC, amorfati0310 commented on vendingMachine/index.js
> +    displays.map(drink => {
크롱 가격이랑 재고가 있는 것들을 displays에 저장해서 다시 출력하는 거여서 map으로 한 번씩 돌면서 출력을 해주었는데 어떻게 고치면 더 좋을까요 ㅜㅜ

2018-03-19 03:07 UTC, crongro requested changes
reduce를 적용해봅시다!
map의 사용도 좀더 올바르게 해보죠.

2018-03-28 23:08 UTC, crongro approved these changes
reduce 적용잘 했네요.
참고로, 아주 짧은 표현은 method chaining을 통해서 좀더 쉽게 표현할 수도 있어요.  다음엔 method chaining을 한번 적용해보도록해보죠.

2018-04-16 02:39 UTC, merged