[woogie]중간미션(자판기어플리케이션)
code-squad/javascript-middle-mission pull request #23
Opened 2018-03-20 06:04 UTC by Imdonguk

2018-03-21 00:41 UTC, crongro requested changes
리뷰남겨요. 
잘 동작하는지도 다양한 값을 넣으며 테스트해보시고요.

2018-03-21 00:41 UTC, nigayo commented on vendingMachine.html
> +	돈이나 사물은 변수나 객체에 저장한다.
주석으로 이렇게 하시는 습관이 좋아보이네요. 
목록은 좋고요.
코드가 어떻게 동작하게 되는지, 흐름을 볼 수 있는 문장도 작성하시면 좋지 않을까요?

2018-03-21 00:41 UTC, nigayo commented on vendingMachine.html
> +	itemData.forEach(function (v){
forEach를 filter와 map을 섞어서 메서드 체이닝방법으로 구현해보세요!

2018-03-21 00:41 UTC, nigayo commented on vendingMachine.html
> +	if(typeof coin === "number" && coin !== undefined && coin > 0){
이렇게 두 줄로 짜는 건 어때요? 

```javascript
if( 어쩌구 저쩌구 ) throw "코인이 ㅇㅣ상한데?";
money = money + coin;
```

2018-03-21 00:41 UTC, nigayo commented on vendingMachine.html
> +	itemData.forEach(function (v){
이 코드도 foreach말고 다른 메서드를 쓸 수 있는지 고민해보세요.

2018-03-21 00:41 UTC, nigayo commented on vendingMachine.html
> +			vendingControl(item);
이름이 뭐하는지 알기 어렵네요.

2018-03-21 02:45 UTC, Imdonguk commented
수정해서 올리도록하겠습니다!

2018-03-21 08:51 UTC, crongro requested changes
수고했어요.
조금더 추가요구사항 남깁니다.

2018-03-21 08:51 UTC, nigayo commented on vendingMachine.html
> +	itemData.some(function (v){
some 함수 안에 함수는 조금 더 수정해보죠.
if 중첩을없앱니다. 
다른 배열메서드를 추가로 쓸 수 있는지 고민해봅니다.

2018-03-21 08:51 UTC, nigayo commented on vendingMachine.html
> +	}).map(function (v){
메서드 체이닝을 시도해서 구현했네요. 잘했어요.

2018-03-27 07:31 UTC, crongro approved these changes
new를 사용한 함수와 , call사용은 
흔하게 사용하는 패턴은 아니지만, new와 call에 대한이해측면에서 잘 구현했어요.

2018-03-27 07:31 UTC, nigayo commented on vendingMachine.html
> +var control = new function(){
생성자 함수를 만들었네요.
객체를 생성하는 함수인데요. 좀더 학습해보세요.

call을 통해서 this를 변경해서 사용했는데, 잘 이해하고 있다고 생각할게요.
혹시 모르면 call의 사용법을 잘 이해해보세요.

2018-03-27 07:32 UTC, merged