New PR
code-squad/javascript-middle-mission pull request #25
Opened 2018-03-27 07:16 UTC by LOG91

다시 PR합니다~

2018-03-27 07:41 UTC, crongro requested changes
리뷰남깁니다.
개선을 좀 해보죠.
그외에도 본인이 개선해야 싶은게 보이면 개선해보세요.

2018-03-27 07:41 UTC, nigayo commented on lotto.js
> +  myTotalPrize += countArr[3] * PRIZE_MONEY.THREE + countArr[4] * PRIZE_MONEY.FOUR +
이 코드를 반복을 돌면서 처리할 수 있지 않을까요?

2018-03-27 07:41 UTC, nigayo commented on lotto.js
> +  return myNum.reduce((prev, curr) => {
reduce를 잘 썼군요.

2018-03-27 07:41 UTC, nigayo commented on lotto.js
>  let setLuckyNumber = array => {
이 함수안에서 동작하는 코드를 함수로 좀더 분리해보면 좋겠어요.
그 크기를 임의로 고민해서 분리해보세요.

2018-03-27 07:41 UTC, nigayo commented on lotto.js
>  function calculateEarningRate(totalPrizeMoney, investMoney) {
화살표함수와 함수선언문을 혼용해서 사용하는 건 학습적인 이유가 아니면 좀 자제해야 할 거 같아요.
일관된 방법으로 구현하세요.

2018-03-28 13:32 UTC, LOG91 commented on lotto.js
>  function calculateEarningRate(totalPrizeMoney, investMoney) {
네 ES6로 변경하겠습니다!

2018-03-28 23:16 UTC, crongro requested changes
내용정리는 잘했고요.

어떤 상황에서 쓰면 유용할 것 같다(또는 주의해야할 거 같다등)는 내용을 항목별 맨 아래에 추가로 써보실래요?  
느낀점을 통해서 좀더 이해도를 높이면 좋겠어요.

2018-03-30 01:56 UTC, crongro approved these changes
정리하느라 수고했어요.
this, call,apply,bind는 중요한데요.
다음미션에서 좀더 이해하면 좋겠네요.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +아직 XOR의 예밖에 모르지만 앞으로 나온다면 적극적으로 배우고 싶다!
비트연산자로만 할 수 있는 구현이 있다기보다, bit연산자로도 구현할 수 있는 것들이 있긴해요.
간단한 연산이나 비교등에서 유리할 듯.

이런거~
var isOdd = number & 1;

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +if내부에 !!같은게 있지 않을까 생각이 든다
네 그럴 수 있어요~ true인지 false인지를 판단하느거니까 그런생각을 가질 수 있겠네요.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +무언가 아직은 안전하지 않은 방법이 않을까 생각이 든다
==의 특성을 이용하는 경우가  아니면 === 를 쓰는게 정확하겠죠?

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +||을 습관화해서 사용한다면 훨씬 더 코드를 깔끔하게 만들 수 있고 가독성에도 훨씬 좋을 것 같다
참고로 es6의 default parameter라는 것이 이부분을 대체할 수 있습니다.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +eval때문인지는 모르겠지만 성능이 좋지 않았던 경험도 있어서 더 외면하게 되었다
eval을 왜 쓰면 안좋은지, 좀더 찾아보면 좋겠네요.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +등장 시기를 아느냐에 따라서 실력이 많이 늘어날 것 같다
아무것도 수행하지 못함, 발견하지 못함 등을 표현하고 싶으면 undefiend를 사용하면 돼요.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +bind는 함수 자체를 반환한다 ()로 실행시켜줘야 하는 셈이다
다음미션을 하면서 좀더 자기것으로 이해하도록 해보세요.

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +지금까지 이해한 것으로는 인스턴스화 할 때 this가 필수라는 점이다
이것도 다음미션을 하면서 이해하기~

2018-03-30 01:56 UTC, nigayo commented on keyword.md
> +함수형 프로그래밍이기에 가능하다는 것을 깨달았고 함수형 프로그래밍이 굉장히 매력적으로 느껴진다
매력을 느끼면 다행이네요~ 
currying 이란 무엇인지 주말에 한번 살펴보세요

2018-03-30 02:05 UTC, crongro requested changes
markdown정리는 괜찮아요. 댓글 참고해서 좀더 학습해보면 좋겠고요. 

lotto는 좀더 수정해보세요.

2018-03-30 02:05 UTC, crongro commented on lotto.js
> +  3: 5000,
js의 객체는 key값으로 이렇게 숫자를 쓸 수도 있어요. 다른 값도 무엇을 쓸 수 있는지 알아보세요.

2018-03-30 02:05 UTC, crongro commented on lotto.js
> +buyLottos = money => {
왜 이녀석은 앞에 const, var, let 등이 없죠?

2018-03-30 02:05 UTC, nigayo commented on lotto.js
>      lottoArray.push(Math.floor(Math.random() * 45) + 1);
코드에서 45가 변하는 숫자라고(46이거나 450이거나 등)생각하고 45를 없애보세요.

2018-03-30 02:05 UTC, nigayo commented on lotto.js
> +  const PRIZE_MINIMUM = 3; // 당첨 최소 개수
이 값을 인자로 받는게 더 낫지 않을까요? 최소갯수가 늘 3개라고 생각하지 않는다면요.

2018-03-30 02:05 UTC, nigayo commented on lotto.js
> +  for (let i = PRIZE_MINIMUM; i < array.length + 1; i++) {
가급적 변수이름을 array라고 하지 마세요. arr까지는 괜찮고. 좀더 나으려면 lottoList 등이 더 나을 듯.

2018-03-30 02:05 UTC, nigayo commented on lotto.js
> +  for (let i = 0; i < array.length; i++) {
for문말고 배열의 함수형 메서드를 써볼래요?

2018-03-30 02:05 UTC, nigayo commented on lotto.js
> +  printResult(countObj[3], countObj[4], countObj[5], countObj[6]);
이렇게 한번 동작하도록 해보세요.
printResult(countObj, [3,4,5,6]);

2018-04-03 02:09 UTC, crongro requested changes
toString 사용이 필요한지?
delete countObj[0]; //아예 안넣기.
reduce를 활용해보세요 ->  lottoArray.push(Math.floor(Math.random() * max) + 1); 

위에 있는 데이터들(mylottos, myTotalPrize, myInvest)를 하나의 객체로 묶기.

console.log(); 지우기 => \n

구현한 코드안에서, 일관된 동작으로 처리되도록 구현하려고 노력. 

countObj = {}는 초기값일 미리 만들필요 없을듯.

주석을 넣는건 좋은데, 약간 줄이면 더 좋겠어요.

2018-04-03 07:14 UTC, crongro requested changes
setLuckyNumber 른 나눕시다. 
자세한건 오프라인으로~

2018-04-05 00:47 UTC, crongro requested changes
함수의 규모가 작아지면서, 복잡함이 조금 줄어들었네요.
불필요해보이는 부분을 조금더 줄일 수 있을 거 같아요.

2018-04-05 00:47 UTC, nigayo commented on lotto.js
> +  computerNumber.reduce((prev, curr) => computerNumberFlag[curr] = true, {});
reduce는 새로운 어떤 value를 반환하는 함수인데, 반환한 결과를 밖에 변수에 저장하고 있어요.
var result = [].reduce();
이렇게 돼야 할 듯.

2018-04-05 00:47 UTC, nigayo commented on lotto.js
> +  let computerNumberFlag = {};
computerNumberFlag 이것을 꼭 만들어야 할까요? 중간에 불필요한 객체를 하나 만드는 거 같아요.
이걸 안쓰고 해결해보세요.

2018-04-05 00:47 UTC, nigayo commented on lotto.js
> +let lotto = {
lotto 를 전역공간에 두고 있는데요.
전역공간을 없애고, 함수끼리 서로 인자로 전달해주면서 처리하도록 한번 해볼래요?

2018-04-06 01:53 UTC, crongro approved these changes
네 로또는 여기까지 하는걸로 해요.
수고했어요.

추가로, 다음부터는 
함수이름은 동사+명사로, 
변수는 명사로(줄여쓰지말기)
잘 만들도록 하세요.

2018-04-06 01:54 UTC, merged

2018-04-06 02:15 UTC, LOG91 commented
네 감사합니다 크롱!