[woogie]중간미션로또생성기
code-squad/javascript-middle-mission pull request #26
Opened 2018-03-29 09:16 UTC by Imdonguk

중간미션(로또생성기)입니다.

2018-03-30 04:06 UTC, crongro requested changes
리뷰남깁니다.

2018-03-30 04:06 UTC, crongro commented on lotto.html
> +	1. 코드흐름 :
설계를 주석으로 상단에 이렇게 표현해보는 건 좋네요.

2018-03-30 04:06 UTC, crongro commented on lotto.html
> +let lottoNumArr = [];
전역변수를 없앨 수 있을 거 같네요.

2018-03-30 04:06 UTC, crongro commented on lotto.html
> +	while(lottoNumber.length !== 6){
6은 변할 수 있다고 가정하고, 함수의 인자로 받도록 하죠.

2018-03-30 04:06 UTC, crongro commented on lotto.html
> +	for(let i = 0; i < lottoCount; i ++){
요 코드는 for문말고 배열의 함수형 메서드를 활용해보세요.

2018-03-30 04:06 UTC, crongro commented on lotto.html
> +	const lottoData = [
lottoData는 어떠한 한정적인 key값에 어떤 value를 할당하는 구조같은데요.

이런 구조는 어때요? 

lottoData = {
   3: {count :0, price : 5000} , 
   4: {count :0, price : 50000} , 
  ...
}

2018-03-30 04:06 UTC, nigayo commented on lotto.html
> +setLuckyNumber([1,2,3,4,5,6]);
setLuckyNumber는 값을 셋팅만 하는 함수같은데요. 
그 내부코드는 많은 동작을 하고 있는거 같아요. 
setLuckyNumber이름을 바꾸기보다, 내부동작을 하위함수로 좀더 분리할필요가 있어보여요.

2018-03-30 04:06 UTC, nigayo commented on lotto.html
> +	const lottoData = [
이런 구조로 변경해보고, 아래 for 문에서 매칭시키는 부분을 수정해보세요.

2018-04-02 07:29 UTC, Imdonguk commented
수정해서 올리겠습니다.

2018-04-02 08:47 UTC, closed without merging

2018-04-03 01:10 UTC, nigayo commented
@Imdonguk  이거 왜 closed 됐죠?