[woogie]중간미션(로또생성기)
code-squad/javascript-middle-mission pull request #30
Opened 2018-04-02 10:57 UTC by Imdonguk

git하다가 실수를 하는바람에 다시 PR날렸습니다..

2018-04-03 02:14 UTC, crongro requested changes
PR다시 날리면서 이거 충돌났네요.

일단 리뷰남깁니다.

2018-04-03 02:14 UTC, nigayo commented on lotto.html
> +	(function prodLotto(){
익명함수가 필요한가요? 
함수안에 동작을 표현하지 말고, 외부함수로 분리하면 좋겠어요.
익명함수는 그리고 성능적으로도 아주 빠른 함수는 아니기도해요.

2018-04-03 02:14 UTC, nigayo commented on lotto.html
> +function setLuckyNumber(luckyNumber){
이 안에 있는 함수들도 inner함수로 표현하지 말고, 밖으로 다 분리하세요.
여기 안에 있는 함수들이 모두 이 함수에 의존되는 함수들이라 setLuckyNumber함수만 괜히 복잡해보이고 있네요. lottoData와 printResult모두 분리하세요~ 

나중에 객체로 구현하면 지금와 유사하게 객체안에 함수를 넣어서 모아둘 수 있긴해요.

2018-04-03 02:14 UTC, nigayo commented on lotto.html
> +function setLottoNumber(){
이름은 set인데, 함수는 무엇을 반환하고 있네요. 함수의 수행로직과 이름을 잘 연결지으면 좋겠어요.

2018-04-05 00:55 UTC, crongro requested changes
조금더 다듬어보세요.

2018-04-05 00:55 UTC, nigayo commented on lotto.html
> +	console.log('로또 ' + lottoCount + '개를 발행했습니다.');
repeatLottos에서 로또를 만드는데, 
그전에 로그를 출력하는게 어색합니다.

2018-04-05 00:55 UTC, nigayo commented on lotto.html
> +	const copyLottoData = JSON.parse(JSON.stringify(lottoData));
이 코드의 동작원리에 대해서, 주석으로 설명을 달아주세요.

2018-04-05 00:55 UTC, nigayo commented on lotto.html
> +	for(let key in copyLottoData){
printResutl함수에서, 
copyLottoData 객체탐색을 두 번하고 있는데요. 
한번으로 줄일 수 있는지 시도해보세요.

2018-04-05 02:11 UTC, Imdonguk commented on lotto.html
> +	const copyLottoData = JSON.parse(JSON.stringify(lottoData));
리뷰반영하여 수정하였습니다

2018-04-06 02:04 UTC, crongro requested changes
코드가 좀더 좋아진거 같아요.
조금 더 수정해보죠.

2018-04-06 02:04 UTC, nigayo commented on lotto.html
>  function repeatLottos(lottoCount){
repeatLottos 이름은 참 구체적이지 않네요.
뭘 왜 반복하는지 알기 어렵습니다.
제가 볼때는 그냥 반복이 아니고, lottoNumArr라는 변수에 값을 추가하는게 핵심인 거 같네요.

2018-04-06 02:04 UTC, nigayo commented on lotto.html
>  function buyLottos(insertMoney){
로또를 사는것보다, 로또번호를 생성한다와 같은 이름이 더 어울릴듯. 
이름에 맞게 동작도 돼야 할 거 같고요.

2018-04-06 02:04 UTC, nigayo commented on lotto.html
>  	lottoNumArr = [];
전역변수에 있는 lottoNumArr를 제거해보세요!

2018-04-09 12:42 UTC, crongro requested changes
Lotto 코드의 흐름이 어색해요.
예를들어 아래코드,
setLuckyNumber([1,2,3,4,5,6], makeMyLotto(50000));

luckynumber함수는 이름만 보면 행운번호를 셋팅한다라고 보여져요. 그런데 알고보면 makemylotto를 만들고있죠. 
그 결과를인자로 받아서 또 무언가 하고, 최종적으로는 결과를 print하고 끝납니다. 

코드에서 동작의 흐름이 자연스럽게 이어지고, 
해당 함수가 해야할말만 좀더 하도록 집중하도록 구현해보세요.

사고의 흐름을 기억하면서 다시 구현해보시면 좋겠어요.

2018-04-09 14:00 UTC, Imdonguk commented
다시 구현해보겠습니다!

2018-04-12 03:11 UTC, crongro requested changes
for문을 없애고, 함수형메서드(고차함수들)로 모두 바꿔보세요.

2018-04-12 03:11 UTC, nigayo commented on lotto.html
> +	checkLottoWinning(luckyNumber){
check보다 좀더 구체적인 이름을 지어보죠.

2018-04-12 03:11 UTC, nigayo commented on lotto.html
> +let pipe = (...fns) => (value) => fns.reduce((acc, fn) => fn.call(lottoObject, acc), value);
이 라인을 이해할 수 있게 설명을 달아주세요.
구체적으로 어떻게 동작하는지요.

2018-04-13 02:25 UTC, crongro approved these changes
좋아요.
메서드 크기와 역할도 좋고요.
pipe메서드의 원리에 대해서 잘 이해하면 좋겠습니다.

2018-04-13 02:26 UTC, closed without merging