[리오] 중간미션 - 자판기 애플리케이션
code-squad/javascript-middle-mission pull request #31
Opened 2018-04-11 08:02 UTC by feanar729

2018-04-12 02:03 UTC, nigayo commented
커밋메시지가 좋네요.

2018-04-12 02:11 UTC, crongro reviewed
leo. 여기 설명한 question_list는 L2과정을 거치면서 계속 내용을 업데이트 하면 좋겠어요. 진행하면서 더 자세하게 알게 될 거에요.

2018-04-12 02:25 UTC, crongro requested changes
구체적인 설계가 좋네요.

너무 깊게 들어가지 말고, 흐름에 집중해서 설계를 하면 더 좋겠어요.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/drinkItem.js
> +module.exports = drinkItem;
exports가 nodejs에서 사용하는 방법인데요.
잘 알아두면 좋겠네요.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +    let notCoinPrint = "숫자만 입력하십시오."
이 경우에는 
if(숫자아님) return ;
무언가하기..

이렇게 짜는게 더 좋겠어요.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +  let shoppingItem = {
shopping이라는 의미가 맞나요? 
객체이름과 속성이름을 좀더 간단히 적어도 좋겠어요.

items.product.
items.stock
items.price 

이렇게 데이터를 구성하는게 명확하고 간단한거 같은데요. 
중첩된 속성간의 의미가 중복되지 않도록 하고요.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +        shoppingItem.sellPrintItem.push(itemList[i].item + "(" + itemList[i].stock + ")");
if문안에 3줄이 뭔가 살짝 중복인데... 개선도전해보시죠.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +    let print = noticeWord.usefulDrink + shoppingItem.sellPrintItem + "\n" + noticeWord.choiceDrink + "\n";
print는 너무 일반적인 이름이니 좀더 구체적으로.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +  } else {
위에서 return했으니, 여기 else는 불필요할 듯.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +    sellItem.sellItemStock.filter(value => {
filter는 push하라고 만든것보다,  boolean상황을 판단하라고 만든 함수에요.
그 의미에 맞는 행동만 하고 다음으로 넘기면 좋겠어요.

2018-04-12 02:25 UTC, nigayo commented on vending_machine/vending_machine.js
> +  var reSelling = getSellingItem(coin);
const와 let으로만 사용해보세요.

2018-04-13 03:14 UTC, crongro requested changes
중간에 오프라인으로 말씀드린 것을 포함해서 수정해보세요~

간단하게!

2018-04-13 03:14 UTC, crongro commented on vending_machine/vending_machine.js
> +const noticeWord = {
상수는 보통 대문자를 써요. 그 활용예제를 찾아보세요.

2018-04-13 03:14 UTC, crongro commented on vending_machine/vending_machine.js
> +let itemList = require("./drinkItem.js");
require 동작을 모듈로더라고 하는데요. 이것이 무엇인지 가볍게공부해보세요.

2018-04-13 03:14 UTC, crongro commented on vending_machine/vending_machine.js
> +    let notCoinPrint = "숫자만 입력하십시오.";
INPUT_NUMBER_ERROR_MSG 처럼 무엇인지를 변수명으로 쓰세요.

2018-04-13 03:14 UTC, crongro commented on vending_machine/vending_machine.js
> +let coin2 = 2000;
테스트를위함이라도 이름이 별로네요.

2018-04-13 03:14 UTC, crongro commented on vending_machine/vending_machine.js
> +const sellItem = getSellingItem(coin2);
sellItem도 별로.. 명사로만 지으세요.

2018-04-18 06:37 UTC, feanar729 commented
다시 만들어 pr보냅니다.

2018-04-20 03:21 UTC, crongro requested changes
오프라인으로 말씀드렸듯이 
함수를 더 작은 단위로 나눠보세요.

2018-04-21 08:43 UTC, feanar729 commented
refactoring을 다시 진행해 보았습니다~ feedback 부탁드리겠습니다

2018-04-23 02:26 UTC, crongro requested changes
함수 크기도 좋고, 
로직도 좀더 단순해진거 같아서 좋네요.

조건상황은 좀더 간결하게 바꿀 수 있을 거 같습니다.
리뷰참고해서 수정해보세요.

2018-04-23 02:26 UTC, nigayo commented on vending_machine/vending_machine.js
>    let INPUT_NUMBER_ERROR_MSG = "[object Number]";
const 가 어울리나요? let이 어울리나요?

2018-04-23 02:26 UTC, nigayo commented on vending_machine/vending_machine.js
> +  // for & in, for & of, filter, forEach, map메서드의 차이점과 실험 해보기
자바스크립트 타입 중에, 순회가 가능한 것들은 모두 for-of 사용이 가능합니다. 
for-in은 어떤 key값을 통해서 접근해야 하는 객체를 순회할때 사용합니다.

2018-04-23 02:26 UTC, nigayo commented on vending_machine/vending_machine.js
> +  if (restCoin === 0 || restCoin < 500 || wantReturnCoin === "반환") {
restCoin이 500 이하면, 0과 비교하는 조건이 포함되는거 아닌가요?

2018-04-23 02:26 UTC, nigayo commented on vending_machine/vending_machine.js
> +    if (wantItem === product.item && product.stock === "재고없음") {
이 함수 시작할때, 
wantItem !== product.item  이면 return 해버리면 좀더 조건상황이 간단해지지 않을까요?

2018-04-23 08:23 UTC, feanar729 commented on vending_machine/vending_machine.js
>    let INPUT_NUMBER_ERROR_MSG = "[object Number]";
let 으로 해야합니다 이유는 변수의 값이 상수가 아니고 변경되는 값이어서 입니다.

2018-04-23 08:23 UTC, feanar729 commented on vending_machine/vending_machine.js
> +  // for & in, for & of, filter, forEach, map메서드의 차이점과 실험 해보기
좀 더 for-in for-of / array function 기능들 실습을 해보도록 하겠습니다

2018-04-23 08:23 UTC, feanar729 commented on vending_machine/vending_machine.js
> +  if (restCoin === 0 || restCoin < 500 || wantReturnCoin === "반환") {
미처.. 생각하지 못했네요;;;

2018-04-23 08:23 UTC, feanar729 commented on vending_machine/vending_machine.js
> +    if (wantItem === product.item && product.stock === "재고없음") {
오프라인 말씀대로 더 쪼개보겠습니다

2018-04-23 09:12 UTC, feanar729 commented
feedback 사항 반영해 보았습니다

2018-04-24 01:10 UTC, crongro approved these changes
네 확인 했어요.
다음에도 함수를 활용하고, 알고리즘의 흐름이 쉽게 되도록 구현해보세요.

2018-04-24 01:10 UTC, merged