[새라] 자판기 애플리케이션 STEP1 (1차 부분 설계 및 구현)
code-squad/javascript-middle-mission pull request #35
Opened 2018-05-18 07:29 UTC by sejungkim

자판기 애플리케이션 1차 부분 설계 및 구현한 내용 PR 보냅니다.
class 사용해서 구현 중인데 어색하거나 코딩 방향이 잘못된 부분 리뷰 부탁드려용 :)
```javascript
> insertCoin(1000);
> 사용가능한 음료수 목록 =>  콜라(1000, 재고2), 사이다(1000. 재고10), 포도쥬스(700, 재고2), 딸기우유(500, 재고4), 미에로화이바(900, 재고9), 물(500, 재고10), 파워에이드(1000, 재고없음)
```
이 부분까지 설계 & 구현 했습니다.

2018-05-21 02:06 UTC, crongro requested changes
전체적으로 클래스가 잘 만들어져 있어요.
리뷰참고해서 일부분 수정하고 진행해보죠.

2018-05-21 02:06 UTC, nigayo commented on vending-machine.js
> +const beverageList = [
이렇게 product 생성자를 통해서 객체를 만들어서 추가하는 건 좋네요. 틀린 사용아닙니다.

그런데 이렇게 배열에 추가하는 게 좀더 낫겠네요.

const newproduct = new Product('콜라',1000,2);
beverageList.push(newproduct);

2018-05-21 02:06 UTC, nigayo commented on vending-machine.js
> +const beverageVM = new VendingMachine(beverageList);
VendingMachine 클래시에 음료리스트를 넣어주는 건 생성자를 잘 사용한 겁니다. 괜찮아요.

2018-05-21 02:06 UTC, nigayo commented on vending-machine.js
> +    this.productList = productList;
클래스의 속성정의는 이렇게 해요. constructor안에서.

2018-05-21 02:06 UTC, nigayo commented on vending-machine.js
> +    this.availableList = this.productList.filter(
OOP개발을 하다보면 이렇게 상태값에 저장할 수 있지만, getAvaiableList함수가 결과를 반환하고 그걸 받아서 처리할 수도 있습니다.
지금은 showAvailableList에서 getAvailableList를 호출해서 결과를 받아서 쓸 수 있겠네요.

2018-05-23 06:34 UTC, sejungkim commented
리뷰 반영하여 자판기 애플리케이션 전체 기능 구현했습니다.

* product 생성자 대신 음료 리스트는 객체 리터럴로 변경했습니다.
* availableList는 getSelectedItem 메소드에서 또 사용해야해서 VendingMachine 클래스 내부 변수로 저장한건데 더 좋은 방법이 있을까요?

리뷰 부탁드려요~ 감사합니당!!

2018-05-23 11:19 UTC, crongro requested changes
클래스 하나에 메서드들 잘 넣었어요. 크기도 크기 않고 함수들이 하는일이 명확한데요. 

selectItem/insertCoin/returnMoney는 요구사항대로 하다보니 클래스 밖에 존재하는 전역함수가 되버렸네요.
이번엔 이 함수들을 클래스 안으로 넣어서  수정해볼래요?

class를 써서 개발하는 구조(OOP)에서는 클래스를 중심으로 객체를 만들고, 클래스 밖에  전역함수를 두진 않아요.

따라서 저 3개 메서드를 현재 있는 클래스 안에서 넣고. 
beverageVM.insertCoin();
beverageVM.selectItem();

이런식으로 동작되도록 수정해보죠.

2018-05-28 02:32 UTC, nigayo commented
어여 수정해서 push 바람~

2018-05-28 07:40 UTC, sejungkim commented
[리뷰 반영 완료]
- 전역 함수를 모두 VendingMachine 클래스 안의 메소드로 변경했습니다!

2018-05-28 08:22 UTC, crongro approved these changes
드디어 한 개의 클래스안에 모두 넣었네요.

구현한것처럼 클래스가 하나의 역할(지금은 자판기에 대한 모든 처리)에 집중하도록 구현하는 게 일반적이죠.  완전 관련이 없다면 모를까 종전처럼 별도 전역함수를 만들필요는 없습니다. 
또 다른 역할이 필요한 것이 있다면 그것을 추가로 클래스로 만들어서 클래스끼리 협력을 하도록 구현하는게 좀더 자연스러울거에요.

2018-05-28 08:22 UTC, merged