[솔로몬] 로또 생성기 step2-1
code-squad/javascript-middle-mission pull request #36
Opened 2018-06-07 08:26 UTC by juchan96

리뷰 부탁드립니다 !_!

2018-06-07 09:24 UTC, crongro requested changes
함수들의 크기가 맘에 들어요.
이름도 좋고 가독성이 좋네요.

몇개 수정해보세요.

2018-06-07 09:24 UTC, crongro commented on lotto.js
> +  let count3 = 0;
let count = {
 3: 0, 4:0, 5:0, 6,0
}

이렇게 객체를 만들어 두고 해도 될 듯. 

이렇게 하면 아래 forEach코드도 약간 변경해야 겠네요.

2018-06-07 09:24 UTC, crongro commented on lotto.js
> +    for (let i = 0; i < 6; i++) {
6과 같은 숫자를 이렇게 코드안에서 하드코딩하지 말고, 변수에 담아서 의미를 만들어두고 쓰세요.

2018-06-07 09:24 UTC, crongro commented on lotto.js
> +  while (lottoNum.length !== 7) {
7이 의미하는 것이 무엇이죠? 여기도 이렇게 하드코딩 노노

2018-06-07 09:24 UTC, crongro commented on lotto.js
> +  for (let i = 0; i < lottoAmount; i++) {
map, forEach 등은 잊은건가요? for 문말고...이제 저런거를 써보세요.

2018-06-07 09:24 UTC, crongro commented on lotto.js
> +    for (let i = 0; i < 6; i++) {
여기서도 filter, forEach 등을 좀 써볼래요?

2018-06-12 06:12 UTC, juchan96 commented
for반복문을 다른 반복문으로 바꾸는 것은 모르겠습니다 배열 형태가 아니라, 숫자를 반복할 용도로 쓰는거라..ㅠ

2018-06-12 07:56 UTC, crongro reviewed
이렇게 나오는게 맞아요? 

console.log(setLuckyNumber([1, 2, 3, 4, 5, 6], 10000));
VM355:84 
    3개 일치 (5,000원)- 5개
    4개 일치 (50,000원)- 3개
    5개 일치 (150,000원)- 2개
    6개 일치 (2,000,000,000원)- 0개
    나의 총 수익은 475000원 입니다.
    나의 수익률은 4650%입니다.

2018-06-12 08:36 UTC, crongro requested changes
전체적인 프로그램 흐름이 좋고, 함수크기도 좋아요.

리뷰남깁니다.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +  const winningNumSum = getWinningNumSum(lottoA, winningNum);
winningNum 도 랜덤하게 생성해보세요. 로또 번호처럼요.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +  const lottoA = buyLottos(coin);
이 함수는 메인함수이면서, 자세한 로직을 감춰놔서 대충뭐하는지 쉽게 알 수 있어서 좋네요.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +  const lottoLength = 7;
이렇게 7 이런 숫자는 가급적 함수의 인자로 받을 수 있으면 더 좋아요.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +    lottoStorage.push(setLottoNum());
setLottoNum함수처럼 하위함수로 분리하는게  좋네요.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +    for (let i = 0; i < lottoLength; i++) {
중첩된 for문은 지금처럼 어쩔수 없이 사용해야 하는 경우는 존재하죠.
하지만 중첩된 구문은 복잡도가 올라간다는 사실은 기억하세요.

2018-06-12 08:36 UTC, nigayo commented on lotto.js
> +  for (let matchNum in count) {
for in 안에 foreach를 쓰고 있어서 복잡해보여요. 반복로직이 중첩되어 있어서요.

for in이 필요 없을 거 같은데 고민해보세요.

2018-06-12 08:50 UTC, juchan96 commented
리뷰 감사합니다!! 수정할 것들 더 고민해보겠습니다아아

2018-06-15 01:16 UTC, crongro approved these changes
네 로또를 여기서 마쳐도 될 듯 해요 .

getRandomNum에서 사용한 객체리터럴 방식을 다음 렉처(할일관리)에서 처음부터 사용해보세요.

2018-06-15 01:16 UTC, nigayo commented on lotto.js
> +  for(let i =1; i < lottoLength; i++) {
for문 대신 for-of 나 
foreach/map 과 같은 메서드를 사용하는게 좀더 보기 좋은 방법이에요.

2018-06-15 01:16 UTC, merged