[새라] 로또 생성기 STEP2 완료
code-squad/javascript-middle-mission pull request #37
Opened 2018-06-12 09:03 UTC by sejungkim

로또 생성기 구현 완료했습니다.
리뷰 부탁드려요!

2018-06-12 09:17 UTC, crongro requested changes
map,  foreach,  reduce등 잘 쓰네요.
함수크기가 작고 전체 코드의 가독성이 좋아요.
몇개 리뷰 남겼으니 살펴보고 수정하세요.

2018-06-12 09:17 UTC, nigayo commented on javascript-lotto/lotto.js
> +function buyLottos(money, lotto = lottoInfo, lottoSetList = lottoList) {
저 위에 lottoList 전역변수는 없애버리고 여기서  lottoSetList = [] 
이렇게 하면 더 좋지 않을까요?

2018-06-12 09:17 UTC, nigayo commented on javascript-lotto/lotto.js
> +  lottoSetList.forEach(lottoSet => console.log(lottoSet));
print는 할 수도 안할 수도 있는 옵션기능일 수 있어요.
따라서 buyLottos의 역할이 아닐 수 있죠.
따라서 buyLottos는 생성한 로또를 만들고, 
출력은 buyLottos 의 반환값을 이용해서 하는 것이 좀더 나을거 같아요.

2018-06-12 09:17 UTC, nigayo commented on javascript-lotto/lotto.js
> +const lottoInfo = {
lottoInfo 데이터 구조가 변경이 가능한 부분(max나 min도 좋고)도 많고, 좋네요.
객체/배열을 잘 활용해서 구조를 잡았어요.

2018-06-12 09:17 UTC, nigayo commented on javascript-lotto/lotto.js
> +  validateMoney(money, lotto.price);
만약 validateMoney 함수에서 오류가 나자나요.
함수를 원래 호출한 이곳에서 throw를 받아서 자세한 에러처리를 하는게 일반적이죠.
하위함수(subroutine)에서 생긴 오류를 거기서 끝내지 말고, 본인(여기서는 buylottos)이 에러처리를 완료해주는 게 일반적이죠.
어떻게 해야 throw를 받아서 에러처리를 완료할 수 있을까요?

2018-06-12 09:17 UTC, nigayo commented on javascript-lotto/lotto.js
> +  for (let winType in winningStat) {
이거 for - in 문이 필요없는지 더 고민해보세요.

2018-06-15 06:00 UTC, sejungkim commented
리뷰 반영이요!
* 이익 계산하는 부분 for-in 대신 reduce로 변경했습니다.
* 유효성 검사하는 부분들(입력받은 돈과 당첨번호) try-catch 사용했습니다.
* buyLottos 함수에서 로또를 출력하는 부분을 빼고 showLottoSetList라는 함수를 만들어 사용했습니다.

2018-06-15 06:39 UTC, crongro approved these changes
리뷰는 남겼지만 참고정도로 이해하시고요.
나머지 코드는 좋네요 .

merge합니다.

2018-06-15 06:39 UTC, nigayo commented on javascript-lotto/lotto.js
> +if (lottoList) {
if 안에 조건상황을 좀더 구체적이면 더 좋아요.
이렇게만 처리해두면 잠재적인 문제가 좀더 있다고 봐야해요.
지금은 buyLottos 의 반환값이 무엇이냐?를 보고 이곳에 적절한 조건을 추가해야겠네요.

2018-06-15 06:39 UTC, merged