중간 추가 미션
code-squad/javascript-middle-mission pull request #6
Opened 2017-10-18 06:34 UTC by sphilee

2017-10-18 09:51 UTC, crongro requested changes
자판기 기능에 오류가 없는지 다양한 상황을 테스트해보세요. 
그러면서 완성도를 더 높이면 좋겠네요.

2017-10-18 09:51 UTC, crongro commented on middleExam.js
> +        if (value.toString() === "[object Object]") {
toString.call 로 타입비교를 정확히 하는게 맞아요.

2017-10-18 09:51 UTC, crongro commented on middleExam.js
> +        } else if (Number.isInteger(value)) {
isInteger메서드의 브라우저 지원범위와 ES표준 어디에 속하는지 찾아볼래요.
그리고 isInteger메서드 polyfill코드를 한번 만들어볼래요? 구글검색해서 복사하는거 금지하시고 ㅎ
polyfill이 뭔지도 모르면 공부해보시고요.

2017-10-18 09:51 UTC, nigayo commented on middleExam3.js
> +        availableDrink += drink.name + "(" + (drink.amount > 0 ? drink.price : "재고없음") + ") ";
요부분 코드만 분리하면 더 좋을 듯.  (drink.amount > 0 ? drink.price : "재고없음")

2017-10-18 09:51 UTC, nigayo commented on middleExam3.js
> +function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }
이코드의 의미가 뭐에요? 갑자기 넣은 이유가  궁금.

2017-10-18 09:51 UTC, nigayo commented on middleExam3.js
> +var drinks = [new Drink("콜라", 1000, 5), new Drink("사이다", 1000, 7), new Drink("포도쥬스", 700, 2), new Drink("딸기우유", 500, 1), new Drink("미에로화이바", 900, 3), new Drink("물", 500, 4), new Drink("파워에이드", 800, 0
object literal로 선언하길 원했는데, 객체를 동적으로 생성했네요. 
new에 대해서 잘 이해하고 사용하시면 좋겠습니다.

2017-10-18 09:51 UTC, nigayo commented on middleExam3.js
> +            if (check === 0 && drinks.length - 1 === index) {
중간에 ()로 연산자 우선순위를 의도적으로 코드에서 보여주면 더 좋을 듯.

2017-10-18 09:51 UTC, nigayo commented on middleExam3.js
> +                    console.log("재고가 없습니다.");
이런 메시지만 묶은 오브젝트리터럴을 하나 만들면 어때요?

2017-10-19 06:44 UTC, crongro requested changes
수정요~

2017-10-19 06:44 UTC, nigayo commented on middleExam.js
> +Number.isInteger = function (value) {
이렇게 하면, 원래 Number의 isInteger가 있는 브라우저에서도 이걸 쓰게 되지 않을까요?

2017-10-19 06:44 UTC, nigayo commented on middleExam3.js
> +                if (drink.name === select) {
이정도는 함수를 좀 나누면 좋을 듯.

2017-10-19 06:44 UTC, nigayo commented on middleExam3.js
> +    drinkMachine.drinks.addDrink("콜라", 1000, 5);
> 
 drinkMachine.addDrink("콜라", 1000, 5);

2017-10-19 08:41 UTC, sphilee commented
@nigayo 수정했습니답!

2017-10-20 01:00 UTC, crongro approved these changes
수고하셨어요.

2017-10-20 01:00 UTC, nigayo commented on middleExam3.js
> +        var drink = new Drink(name, price, amount);
요 코드는 Drinks 생성자 안에서 초기화 하는것도 좋을 듯 하네요.
지금도 괜찮아요.

2017-10-20 01:00 UTC, merged